# This is a basic workflow to help you get started with Actions

name: Update fork

env:
  UPSTREAM_URL: "https://github.com/dabreadman/go-web-proxy.git"
  MAIN_OR_MASTER: "main"
# Controls when the action will run. 
on:
  schedule:
    - cron: "0 18 * * 1"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set upstream
        run: git remote add upstream ${{ env.UPSTREAM_URL }}
      - name: Set email
        run: git config --local user.email "action@github.com"
      - name: Set username
        run: git config --local user.name "GitHub Action"
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream
        run: git merge upstream/${{ env.MAIN_OR_MASTER }} --allow-unrelated-histories
      - name: Push changes 
        run: git push 
